### ISSUE TITLE
Updating and Expanding Rule 1.2: Assisting Other Players In Breaking Server Rules

### ISSUE THREAD

**Issue by RangerMK01** [EarthMC/EarthMC.net#104]
**Exact wording of the rule:**
**1.2 Benefiting from or assisting others in breaking server rules.**
Players found intentionally assisting, knowingly participating in, or knowingly benefiting from another player's breaking any of the rules listed on this page are liable for the same punishment as the original rule breaker.

**How will this rule affect the community:**
Under the current definition and based on the past rulings of both Fix and Karl, players that participate in or benefit from another player's rule-breaking are not liable for any punishment. If someone alted and sniped a town, then gave it to me while I was aware of their status as an alt, I would not be punished at all. Players that are knowingly part of any type of rule breaking should be liable for the same punishment as the original rule breaker.

**Do you think this will benefit both the staff and the players:**
We currently have players who have gotten free of bans or other punishments despite benefiting immensely from another player breaking the rules. This is unfair to both the players, and to the staff who are unable to act on a situation where they should be able to. Players should not be able to abuse or take advantage of someone else breaking the rules as it gives them an unfair advantage and excuses behavior that would be punished if the situation was only slightly different.

**Comment by ghost** [comment]
+1

**Comment by CorruptedGreed** [comment]
I agree with this, as it's not fair for players to break any rule through a proxy.

**Comment by Mihailovi** [comment]
Absolutely agree with this.

**Comment by ghost** [comment]
I agree there are potentially lots of nations and towns who deliberately use and benefit from having one banned player to break rules for them indiscriminately and face no consequences or repercussions through alt accounts.

**Comment by PoppyK** [comment]
One area we see this is in the form of alting.  The key factor too, or root of the towny game, is residents.  When that factor is being exploited, and players are cheating in using "extras" it is simply not acceptable, breaks the game and gives an unfair advantage.  I would like to see alters ipbanned. If evidence points to an alt, then the main user should be banned as well.  Its only fair...since the main is the one breaking the rule. 

We also need this in areas of duping/hiding duped items, doxxing,  and more.  I'd like to see this rule updated to weed out those who are just here to break the game.

**Comment by maxifunseeker** [comment]
Yeah, I think it's really not fair when the player knows there's an alt in his or her town, but not reporting it while not getting punished for that under current rules

**Comment by BBrotherss** [comment]
Completely agree with this new rule!

**Comment by SuperChrisBoy** [comment]
This should be in the rule long ago.
