### ISSUE TITLE
New Rule: Make Carpet and Rail Dupers Illegal

### ISSUE THREAD

**Issue by RangerMK01** [EarthMC/EarthMC.net#105]
**General wording of the rule:**
The use of any exploit, redstone machine, or other method to create copies of any item (duping) is banned. This includes carpet duping, rail duping, and of course, gold duping.

**How will this rule affect the community**
All server exploits that are potentially dangerous to either the server, the player economy, or the player experience should be prohibited. While most kinds are, certain types of dupers such as carpet and rail dupers are allowed currently. These duping machines can cause extreme lag, or even crash the server, and they ruin any sort of market for carpets (wool) and rails (iron).
Banning all forms of dupers, regardless of item or type of duper, would allow for a more fair experience for all players with a reduced potential for lag or server breaking machines.

**Do you think this will benefit both the staff and the players**
This would keep things consistent with the server policy of no exploits and help discourage other kinds of exploiting. If we allow even a couple types of exploits or method of duping, that will encourage the use of other exploits and dupes that players may deem fall into the same category as carpets or rails. Ensuring that no duping of any kind occurs ensures a fair and more stable player economy, a better experience for players who have invested time into their shops and farms, and more clear rule standards for the staff team when it comes to potential exploits and duping incidents.

**Comment by gabeeebaby** [comment]
I disagree with this suggestion for multiple reasons. First of all, carpet and rails are used for large projects that increase the attractiveness of the server, such as carpets being used to make map art and rails being used to connect towns. These dupers are different from the other types of dupes and these duping methods are not possible with other items. I don't think this encourages other types of dupes/exploits because they are not used to gain power, influence, or in-game money, which is what most dupers of valuable items are after. For carpets, crafting is inefficient due to the only easy way to get wool being through villagers, as mob spawning/despawning is very unpredictable. The only way I could see the community accepting this rule change would be if there was an easier way to get wool. This could be implemented through a custom crafting recipe for carpets that would be seen as fast and easy to get as duping carpets. It could also be fixed through mob spawning being reimplemented, but I see this as highly unlikely due to the many issues it would cause for the server. For rails, banning duping of it would make large rail networks seem unattractive for many to make, and travel between non-capital towns less likely, destroying some of the "geo-political" part of the server.

**Comment by jkmartindale** [comment]
Either way, I definitely think there should be clarification on the rules page of what dupes are allowed or explicitly that no dupes are allowed. Otherwise this whole situation is just plain confusing.

**Comment by GreenGuyyy** [comment]
Carpet and Rail Duping should be allowed as many map art makers use carpets for their designs, requiring thousands of carpet, so having duping makes it 1000 times quicker. And as for rails, countries make large railways that require hundreds of rails, and this rule change would make this a lot faster then this

**Comment by solamint** [comment]
Want mapart to be 100g for a 1x1? Ban carpet dupers. Banning carpet dupers can make it harder for mapart to be made, and can seriously destroy the server and economy. Mapart makers would have to buy more sheep and dyes, making sheep become more scarce, and would pack more entities in a chunk, causing lag for days. A duped can be used when needed, and barely lags the server, and doesnt make frames drop.

**Comment by Lagann311** [comment]
Just saying, you don‘t need any wool for map arts. Concrete powder depicts the same color and is much cheaper.

**Comment by Oln123** [comment]
I don't think its a good idea just to allow carpet duping because it helps you do things easier.
That's what every dupe does.
I also think the ability to dupe carpets just makes them worthless.
Imo it messes with the economy to have duping in any context allowed.

**Comment by FutureLemon** [comment]
Duping in any way, shape or form shouldn't be allowed the amount of lag and chaos a carpet duper can cause is insane. I remember building a carpet dupe maching and it actually crashed the whole server I would not recommend that to anyone.

**Comment by solamint** [comment]
Have you tried making concrete? Once I tried mass creating concrete and I crashed a server. Duping carpets is the best you can do. Anyways, you cant do much with carpets once theyre made, until you start making another mapart.

**Comment by Cactusinapumpkin** [comment]
Making concrete by stacking it and letting it fall effects the server more than carpet duping and rail duping is not allowed.

**Comment by Cactusinapumpkin** [comment]
The reason why carpet duping is allowed is so everyone doesn’t have 20 sheep in different colors and then they despawn randomly. Wool is scarce in emc and carpet duping fixes that issue as railroad modified crafting recipe fixes the gold railroad issue.

**Comment by Cactusinapumpkin** [comment]
Really we should be talking about the method to make concrete. The way I do it and how others should to prevent server lag is by putting it in ur off hand and using a pick instead of stacking it. I stacked it once and the falling powder stopped falling and got stuck in the air and it was extremely laggy like the frame rate will go to 1fps and was worse than the large firework explosions.

**Comment by solamint** [comment]
We need a custom recipe for concrete, like 8 concrete around a bucket of water gives you hard concrete. On the other hand, stop trying to wreck the mapart economy. The reason we sell maparts at 2-6g (well, the small 1x1s and 2x2s) is because we can make them easy. You wouldnt want one 1x1 to cost 20g because of how hard it is to get wool. This issue is a stupid way to make another unnecessary challenge to mapart makers. Rails, on the other hand, IDGAF about.

**Comment by FutureLemon** [comment]
> We need a custom recipe for concrete, like 8 concrete around a bucket of water gives you hard concrete. On the other hand, stop trying to wreck the mapart economy. The reason we sell maparts at 2-6g (well, the small 1x1s and 2x2s) is because we can make them easy. You wouldnt want one 1x1 to cost 20g because of how hard it is to get wool. This issue is a stupid way to make another unnecessary challenge to mapart makers. Rails, on the other hand, IDGAF about.

2-6 gold is already pretty expensive for a simple map...

**Comment by 10op10** [comment]
> The reason we sell maparts at 2-6g

Lmao, map arts are not sold for 2-6g, people charge anywhere between 50-350g for the simplest shit, and ik this because I'm an admin on the server, and I also think the price is too high, also maybe use your brain and recycle concrete like we did before carpet duping was legal.

**Comment by GitMocc** [comment]
Since carpet duping is allowed, the market for carpets is gone already, and there is no harm in making map-art or connecting two towns across a sea or something. I have never seen people selling rails or carpets in all 3 years of me playing EMC. Gold duping is VERY different from carpet duping, One is a currency, one is not valuable whatsoever.

**Comment by nipdip** [comment]
I've made a possible 1.6 rule about item duplication(issue 125) and I think while gold and TNT dupers should be illegal, due to the problem they pose to the economy, lag, and the balance of power, but carpet and rail duping are relatively innocent, and din;t give players an extreme edge over their non-duping counterparts. Actually I think carpet and rail duping is better legal since they can make more varied map art and improve national and international infrastructure.

**Comment by ketchupdrinker** [comment]
@RangerMK01 Is this an official rule or a rule suggestion, because I see other posts that state that carpet duping is allowed at the moment and I'm confused.

**Comment by jkmartindale** [comment]
> @RangerMK01 Is this an official rule or a rule suggestion, because I see other posts that state that carpet duping is allowed at the moment and I'm confused.

There's nothing on the rules page that says carpet duping is allowed, but pretty much all the mods say it is. I think this was an attempt to make it more clear which is correct.

**Comment by shirazmatas** [comment]
majority verdict is people do not want this.
