### ISSUE TITLE
[Rule change] 3.3 Claim Blocking.

### ISSUE THREAD

**Issue by ghost** [EarthMC/EarthMC.net#106]
**Exact wording of the rule**
Exactly how the rule should be written on the rules page.

**Current wording:**
> 3.3 Claim blocking.
> “Claim blocking” is referring to the act of deliberately placing claims near a town in order to block its expansion. This includes placing a new town next to another with the intent of blocking their expansion.
> 

>**Images of example of claim arms**

> 
> A town's claims count as blocking if they create long arms of claims protruding from their town like in the images above. These arms are an issue as they do not only block existing towns but also take up large areas where future towns could otherwise be created.
> 
> Only mayors of towns being claim blocked may report breaking the rule as claiming along someone's border is fine if all involved towns agree on it.
> 
> All claims which staff concludes to be blocking a town will be removed without any refund. Players found to be claim blocking more than once may be warned.
> 
**New wording:**
3.3 Claim blocking.
“Claim blocking” is referring to the act of deliberately placing claims near a town in order to block its expansion. This includes placing a new town next to another with the intent of blocking their expansion. _How near is too near is decided on a case by case basis by staff._

**Images of example of claim arms**

**A new example Image of hollow claims being used to block, one picture of dynamic map and one picture of the towny chunk map side by side to show hollowness**

A town's claims count as blocking if they create long arms of claims _or boxes/enclosed shapes_ protruding from their town like in the images above. These arms _/hollow claims_ are an issue as they block existing towns but also take up large areas where _neighboring towns could claim._

**Only** mayors of towns being claim blocked may report breaking the rule as claiming along someone's border is fine if all towns affected agree on it.

All claims which staff conclude to be blocking a town will be removed without any refund. Players found to be claim blocking more than once may be warned and denied the ability to place outposts all together.

**How will this rule affect the community**
I think this should clear up a little confusion by:
A. Explicitly stating that hollow claims used to block towns are illegal too not just arms and...
B. Removing the section about blocking the creation of new towns as it was unenforceable due to the fact you could not make a ticket about claim-blocking unless your town existed and was being blocked.
C. Took out the part about outposts as you can't make towny outposts on the server.

**Do you think this will benefit both the staff and the players**
This should benefit staff as it is a clearer rule based on the precedent set on the server in most cases and it should make the rule clearer to understand for players, for the same reason.

**I have put in italics any new wording to the rule just to make it extra clear what has been changed. Let me know your thoughts and anyway this rule can be improved based on how it is enforced on the server.**

**Comment by MineHero43** [comment]
Or just remove the claimblocking rule since it’s a waste of time, tickets and a clear overreach of mod powers to have them constantly sniffing their noses and picking sides in disputes between towns and nations. These matters should be resolved by the players as it’s meant to be a geopolitical sandbox, staff shouldn’t be the ones deciding the outcome of disputes. If you get out-claimed/out-smarted by a neighbouring town, tough Nookies. Constant mod intervention takes away the challenge. Geopolitics is supposed to be about the survival of the fittest.

Focus on rule breaking that actually harm the server such as hacking, exploits etc.

Good re word though, at least it makes things a little clearer. 

One suggesting I'd make is adding that every single 'claimblock' thats removed should be refunded. Excuse my language but it's fucking annoying to save up lots of gold to claim land for your town only to have it removed because your smaller neighboring town is too poor and upset. Mods just /t unclaim huge amounts of land like its nothing. Having claims removed is one thing, not getting the gold refunded is another which just rubs salt on the wound. The gold was earned fairly and fairly spent and therefor should be refunded totally.

**Comment by ghost** [comment]
It would make sense, as MineHero43 said, to remove the rule because in real life what is essentially claim-blocking has sparked [a dispute between Liechtenstein and Czechia](https://en.wikipedia.org/wiki/Foreign_relations_of_Liechtenstein#Relations_with_individual_countries).

**Comment by KarlOfDuty** [comment]
The reason we don't remove claim arms without a nearby mayor reporting it is both because the claim arm may be part of something the nearby towns have agreed to (like claiming a border wall on the edge of your nation) or that there is no one around to be bothered by the claim arm in which case I think it's just a waste of time for both the player in question and the staff.

**Comment by ghost** [comment]
> The reason we don't remove claim arms without a nearby mayor reporting it is both because the claim arm may be part of something the nearby towns have agreed to (like claiming a border wall on the edge of your nation) or that there is no one around to be bothered by the claim arm in which case I think it's just a waste of time for both the player in question and the staff.

Why was this closed? @KarlOfDuty

**Comment by ghost** [comment]
> The reason we don't remove claim arms without a nearby mayor reporting it is both because the claim arm may be part of something the nearby towns have agreed to (like claiming a border wall on the edge of your nation) or that there is no one around to be bothered by the claim arm in which case I think it's just a waste of time for both the player in question and the staff.

Nowhere in the new wording of the rule does it say that staff will remove claim arms without a nearby mayor reporting it? the changing in the wording was to make it clear clear hollow claims count as claim arms if they're used to block a town. There's not a single mention of allowing staff to remove claim arms without it being reported by an adjacent affected mayor?

**Comment by ghost** [comment]
> The reason we don't remove claim arms without a nearby mayor reporting it is both because the claim arm may be part of something the nearby towns have agreed to (like claiming a border wall on the edge of your nation) or that there is no one around to be bothered by the claim arm in which case I think it's just a waste of time for both the player in question and the staff.

"Only mayors of towns being claim blocked may report breaking the rule as claiming along someone's border is fine if all towns affected agree on it."

This is the wording of the rule so I don't understand where you think it suggested that claim arms should be removed without a nearby mayor reporting it. ._.

**Comment by KarlOfDuty** [comment]
I see, there were two issues open on this at the time, must have gotten them confused

**Comment by KarlOfDuty** [comment]
We have now updated this rule according to a different suggestion.
