### ISSUE TITLE
(new rule) Banning town boarder exploits.

### ISSUE THREAD

**Issue by Mojo2703** [EarthMC/EarthMC.net#122]
Right now when you place a block in a border of a town the block takes a second to disappear and is commonly exploited with scaffolding to quickly place and climb blocks before they disappear even though you're in a town's border. This bug not being banned right now makes building walls pointless since anyone can just climb over it even if you built the wall in your boarders.

**Comment by Goosius1** [comment]
Hi,

To spare increasing mod workload, I believe this can be countered with a simple tip.

Already if your walls are only 1-3 blocks in from your border, they are (in a sense) already pointless regardless of this exploit.
--> because attackers can simply build a scaffold OUTSIDE your border then jump the short distance in/out.

Thus your walls should be min 4 blocks in from your border. I suggest simply guiding defenders to buikd their 5 blocks in (or more). 

If this guideline is followed, walls will be as effective and useful as if the glitch was not there.

**Comment by Goosius1** [comment]
(Edited)

Hi,

Im not sure if this is a real exploit in practical terms.

Already if your walls are only 1-4 blocks in from your border, they are (in a sense) already pointless regardless of this exploit.
--> because attackers can simply build a scaffold OUTSIDE your border then jump the short distance in/out.

So with walls which are already secure in the normal way (5 blocks in) does the exploit work??

i.e. an can exploiter both glitch up and make a 3 block running jump at the same time?

**Comment by Mojo2703** [comment]
The glitch is that no matter how tall your wall is the delay before a block is deleted when being placed can be used to climb walls that you should not be able to get over in any way.

**Comment by Goosius1** [comment]
Does it work for getting over a walls which is 5 blocks in from the border?
E.g

 Wilderness (border) 1 2 3 4 Wall.

**Comment by Mojo2703** [comment]
Yes, it can get over walls that are well within a town's borders and at any height.

**Comment by Goosius1** [comment]
Ohhh...so (to confirm) it can be done while well inside the townblock ---anywhere in the town?

**Comment by Mojo2703** [comment]
Yes it can be done anywhere in the town.

**Comment by Goosius1** [comment]
That's pretty serious 
(especially w/ Beta war system, where as expected, effective walls matter a lot more).

I'm not totally familiar with EMC rules, but is this type of exploiting not already covered by the existing rules ??

(i.e. if a player is exploiting any bug, for duping, xraying, flying, climbing over walls etc, or any other exploits we don't even know about yet, then surely everybody knows that this is not allowed and will result in punishment if caught)

**Comment by Goosius1** [comment]
Ye here it is:

Rule:  "Players are not allowed to take advantage of apparent server bugs or otherwise exploit technical oversights. Players found taking advantage bugs or technical oversights without notifying staff may be permanently banned."

This rule seem to cover the identified exploit from a rules point of view.
Is a new rule actually needed?

**Comment by Mojo2703** [comment]
I was told by a staff member when I tried to report someone for using it that this isnt against the rules.

**Comment by Mojo2703** [comment]
According to DocW on the ticket listings Eagle ruled that this is currently allowed but I assumed that meant it just wasnt listed in the rules.

**Comment by KarlOfDuty** [comment]
We do not think block glitching should be banned at this time, it isn't really something any servers I have seen punish for, it's just a part of the game.
