### ISSUE TITLE
Rule 2.4

### ISSUE THREAD

**Issue by docwhomc** [EarthMC/EarthMC.net#126]
It appears @DasCodes neglected to make this to get player feedback before making the rule change in 90a5767df536837b8a4136f8775d3693db977d33, so here we go...

### Wording prior to the rule change

> **2.4 Toxicity.**
> Toxicity is not allowed on this server. Toxicity in chat includes but is not limited to:
> 
> - Insulting others.
> - Bullying/harassing others.
> - Name-calling.
> - Vulgar chat, using explicit language, inappropriate content which would be obscene or lewd talk.
> - Talking or threatening about self-harm, or other deeply negative experiences.
> - Leading or encouraging violence or hatred towards other players.
> - Constructing buildings/pixel art that can be considered racist/sexually explicit or containing hate speech/symbols.
> - Being malicious, toxic towards the staffs or anyone.
> - Messages with sexual characters and sexual harassment.
> - Hate Speech, discrimination in any form, such as negative comments related to skin color, race, sex/gender, sexual orientation, disability, religion/beliefs, or other personal qualities.
> 
> Toxicity is evaluated on a case by case basis and staff has final say in what is considered toxic behavior. Repeated behavior may lead to warnings, mutes and eventually a permanent ban.

### Wording after to the rule change

> **2.4 Unwanted behavior.**
> Listed unwanted behavior is not allowed on the server. Unwanted behavior includes:
> 
> - Explicit forms of bullying.
> - Repetitive use of derogatory terms.
> - Comments encouraging self-harm.
> - Inciting violence or explicit forms of hate speech against racial and social minorities.
> - Explicit talk about sex.
> 
> Toxicity is evaluated on a case by case basis and staff has final say in what is considered toxic behavior. Repeated behavior may lead to warnings, mutes and eventually a permanent ban.

What do players think of this change?  Are you in favor of it?  Do you think it should be reverted?  Do you think it should be rewritten again?

**Comment by 10op10** [comment]
What exactly is considered "Explicit forms of bullying" it will still cause mods to make mistakes because mods each have their own interpretation of the rule, like I got muted for saying retard, yet you see people calling others retarded and the other mods have no issue, this is part of the issue, the rule isn't clear enough

**Comment by docwhomc** [comment]
I agree, the new version of the rules isn't more lenient, it's more vague.  The reason @FixTheAdmin suggested this rule change was that he realized the previous wording was too vague.  Several of us expressed reservations about the wording, but "the administration" proceeded to implement it without consulting with the player base until after the change was made.

Considering the channel where we expressed our reservations about this new wording was deleted for the alleged purpose of encouraging discussions about rule changes to occur here (rather than in the staff server) to enable players to weigh in, I find it utterly hypocritical that the change was made in this fashion.

**Comment by DasCodes** [comment]
Which part is vague to you?

**Comment by docwhomc** [comment]
To start off with, "Explicit forms of bullying".  What counts as bullying?

**Comment by FixTheAdmin** [comment]
Hey!
The new rule is more lenient and more in line with what I want staff to punish for. It should also make it easier for players to understand and live up to. Of course it still has some subjective aspects (explicit bullying) but I wholeheartedly disagree that it's more vague compared to the old rules. The old rules disallowed insulting, being malicious and name-calling. Those have been removed. To me that is very difficult to live up to on a geopolitical sandbox and it gives staff too much power warning players for their subjective understanding of the rule. 

To answer the question on bullying, the new rule was written to combat severe cases of bullying (explicit) where there is no doubt a player is being exposed to psychological trauma. Comments such as someone saying "dickhead" or other mean remarks should not be warnable since I have a hard time seeing how that would equal explicit bullying even with the issue of subjectivity in mind. If a moderator is in doubt if a player is being exposed of explicit bullying I hope they DM and we can go over the case.

**Comment by FixTheAdmin** [comment]
I should add that we have new chat filter that removes messages based on the above rule. I thought it would be in line to have the official rules synced with what the filter removes.

**Comment by shirazmatas** [comment]
I think the rule change is better and more easy to understand

**Comment by Shiachanthedevil** [comment]
tbh, I think the old one is more detailed, but the new one is easier to understand

**Comment by Oln123** [comment]
What words were removed from the chat filter ?

Edit: Before it has been suggested that bypassing the chat plugin is against the rules. I get that, but I feel like something like. 
"There Is a chat plugin that removes words deemed to be against rule 2.4 and bypassing this plugin is against the rules"
should be in the rules.

**Comment by solamint** [comment]
Please make the chat filter more PG13-orientated, with certain words allowed, such as but not limited to, "Fuck", "shit", "bitch", "piss", "cum" c̶h̶a̶l̶i̶c̶e̶, "ass", "dick", "cock".
Allow sexually suggestive mapart, but no visible nipples, vaginas, penises, or any other reproductive organ. 
Boom, 2 birds with one stone.

**Comment by AmphireYT** [comment]
> Please make the chat filter more PG13-orientated, with certain words allowed, such as but not limited to, "Fuck", "shit", "bitch", "piss", "cum" c̶h̶a̶l̶i̶c̶e̶, "ass", "dick", "cock".
> Allow sexually suggestive mapart, but no visible nipples, vaginas, penises, or any other reproductive organ.
> Boom, 2 birds with one stone.

yes

**Comment by nipdip** [comment]
What about C*nt and racial slurs? Should they be allowed or not?

**Comment by DasCodes** [comment]
@EmattpoYou It does not filter any specific words, it checks the context and removes it if necessary.

**Comment by FutureLemon** [comment]
We just need to censor certain words @DasCodes especially some equally harsh slurs for a minority group on EarthMC like in this issue https://github.com/EarthMC/Issue-Tracker/issues/1104

**Comment by ketchupdrinker** [comment]
So recently I received a warning for saying in chat the following (which is a joke):
**"POV: You're my hamster, prepare to go in my ass"**
I thought the 2.4 rule was supposed to be lenient about such things above which are clearly satirical.
Can you please make the unwanted behaviour category less vague for explicit talk about sex because minecraft is a PG-13 game (ERSB rating system requires online creative spaces to be 13+ or 18+ depending on the availability of wording) so it doesn't make sense to attempt to remove something that is clearly a joke and is even vaguely sexually related in the first place.

Along with the rule specification I would like the warn removed for it because the ticket seems to be taking a while to process with no attempt to respond or resolve it from the mod who warned me.

**Comment by coblobster2** [comment]
I think this was a terrible move because it made this rule more vague and less to mod. Which is ironic with new map art rules. These rules seem to allow more toxicity which is just plain bad.

**Comment by KarlOfDuty** [comment]
This already seems to have been implemented.

**Comment by solamint** [comment]
what was implemented? the issue was opened to discuss what needs to be changed, not to add onto 2.4 when it was originally changed due to people's unhappiness and harshness of the enforcement of 2.4.
