### ISSUE TITLE
Amendments to the Rules

### ISSUE THREAD

**Issue by docwhomc** [EarthMC/EarthMC.net#127]
There should be a prescribed process that all rule changes must follow, regardless of from whom they originate.

Some ideas for such a process:

- a mandatory public comment period of at least one week.
- following the public comment period, both the staff team and the player base as a whole should vote on the rule change
- if both the staff team and the player base approve the rule change, it can then go to the server owner for approval

**Comment by DasCodes** [comment]
While we try to make rule changing more transparent before making them live, but it'll never be a mandatory thing to notice or get approved by others beforehand. The owner and admins hold the exclusive right to update the rules as they feel is right for the server and the community with or without any prior notification.

Everyone is welcome to suggest a rule change, however. But we'll try to notify about it before changing them.

**Comment by docwhomc** [comment]
What was the point of removing the cooking rules channel then?  Karl said it was so there could be public input and transparency.

**Comment by Oln123** [comment]
While fix _can_ do what he wants to his server.
It doesnt mean he should do what ever. Like just because you have the legal right to do something doesnt mean you should.

Edit:  Basically my point is that while fix can do what he wants, doesn't mean he should and the fact that fix isn't required to do something isn't really an argument against the thing doc is suggesting. 
This is like 
me: Add a war plugin
eagle: fix isn't required to add a war plugin.

The fact that fix doesn't need to follow a suggestion isn't an argument against the suggestion its self
