### ISSUE TITLE
I want to had move mods able to use

### ISSUE THREAD

**Issue by ghost** [EarthMC/EarthMC.net#128]
Mods That are not malicious such as hacks, duping, book bot, baritone and anything that can cause an advantage over other Mods not malicious like Optifine, Notebot, Litescmatic, and many more 

This will affect the community by having fewer players perm banned for not malicious stuff like Notebot it's a bot that can be able to play music this will be able to have more players to have more fun like play music at parties in-game and have fun. The server will have more fun with many more mods 

**Do you think this will benefit both the staff and the players**
This will benefit both staff and players because staff can take a break from banning way too many players. Players will be able to have more fun with other mods like a music bot mod or tracers so you can make sure your safe at all times 

**Please use <https://github.com/EarthMC/Issue-Tracker> for issues other than the EarthMC.net website**

**Comment by jkmartindale** [comment]
Player movement mods aren't allowed because even if they don't offer a PVP advantage, they allow players to bypass AFK detection.

> tracers so you can make sure your safe at all times

This is a whole different beast. EarthMC rules on mods are so that players with allowed mods only have cosmetic/informational changes so that they don't have any significant advantage over players with vanilla clients. Being able to trace players through walls and underground definitely defeats that purpose, as players can't get the same information with vanilla and Dynmap.

**Comment by KarlOfDuty** [comment]
The comment above explains my thought on it pretty well too.
