### ISSUE TITLE
Fishing Players In Claims

### ISSUE THREAD

**Issue by DCDylanc123410** [EarthMC/EarthMC.net#137]
**Exact wording of the rule**
According to the current EMC rules. Rule 1.3 states: 

1.3 Technical errors and server exploits.
Players are not allowed to take advantage of apparent server bugs or otherwise exploit technical oversights. Players found taking advantage bugs or technical oversights without notifying staff may be permanently banned.

Along with that Rule 2.1 currently states:

2.1 Teleport traps
The act of tricking players into teleporting to a specific location or person just to kill or trap them is not allowed. This used to be allowed but a lot of players abused it to the degree players voted to forbid it.

Normal traps that don't involve players blindly teleporting into them are allowed however, as long as the player doesn't get stuck for a longer period of time.

I don't believe the rules themself need to change but our way of enforcing them does. There are many situations in EMC where both of these rules above get broken but we end up unsure what to do about it. In this particular issue I am talking about **Fishing Players in Claims**

**How will this rule affect the community**
I along with some other mods and EMC community members feel fishing in claims should be against the rules in some way shape or form. I want you to think. Think about how often people get unfairly killed in claims due to fishing. How often players are unable to play or teleport due to being fished. It bypasses the whole reason why we can have pvp off in claims to begin with. I truly believe fishing players in claims should be against the rules for these reasons:

-  People are fishing players from inclaims to out of claims to kill them even in non pvp zones.
-  Players are fishing players in claims from tall buildings in non pvp areas to kill them.
-  Players are killing pvp protected players in claims and out of claims by building tall structures and fishing the players below which then kills them due to fall damage
-  Players are fishing players to prevent them from being able to tp inside or outside of claims even if they are not killing them they tug enough so they move so they cant tp
-  Players are fishing players in claims to block their vision because sometimes when a player is fished a bobber is showed over the fished players eyes which block their view
-  Players are fishing people in claims to achieve pvp through pulling them into traps, dragging them to pvp areas, the wildness, or up in the air to achieve pvp/killing other players in claims

As seen this is being used to kill, attack, and/or trap players within claims that are marked as no pvp zones. Along with this many players fish at nation spawns or even the world spawn to kill unsuspecting players even if it is a no pvp zone. Players are also using this to block players views and to prevent players from being able to teleport away if needed. Some players end up being fished for even several minutes at a time still unable to teleport away. This has been an issue for mods and players alike and needs to be solved. Along with this it also bypasses pvp protection players because they can still take fall damage. This will become a even worse problem once the new war plugin comes about because players will be able to kill others as soon as they spawn by fishing them up into the air instead of waiting to kill them with pvp. This is because players will be pvp protected when they first spawn at a nation once the war plugin comes about. Fixing this issue is something that will help all of us as a whole and make EMC a better and safer place to be.

**Do you think this will benefit both the staff and the players**
As mentioned above staff and players will benefit from this because it affects both alike. Players and mods alike get fished in claims sometimes repeatedly for even hours at a time. This can make the game almost unplayable for those affected during that time. Along with this I truly feel this is moderatable and easy to moderate as well. Just like the scaffolding glitch once it is against the rules the majority of players will stop doing it. Along with that players often report other players for their wrong doings which will help get any players still doing it. I do not feel this will give the mods any extra work.  It would actually make doing most spawn trapping and even harassment tickets more manageable because many of those tickets include some form of being fished in claims. Our main problem right now is that we are unsure how to handle these certain tickets pertaining to this issue because it's hard to say if its breaking the rules or not. If this became against the rules we will be able to get more tickets done because we will know how to respond to them which will help the entire community as a whole. I feel together we can help make EMC a funner, safer, and a more playable place.  **Fishing Players in Claims should be against the rules.** Thank you

**Comment by 10op10** [comment]
Yes great idea, removing the pvp aspect even more, its bad enough ppl chilling in claims and the only way to get them out is rodding, your suggesting that EarthMC should completely wipe the pvp aspect because your salty about dying?

**Comment by amazingmoe** [comment]
First off, I’d like to say here that I’m not a pvper in the emc community, however, since I have participated in multiple fights and whatnot, I will say that fishing people in pvp zones are an essential aspects to fights because people will take advantage of claims to not fight, but try to cause their own type of havoc such as shooting arrows or using cannons. By fishing someone out of claims, all that a person needs to do is run the opposite way to negate the effects of a basic fishing rod. This is all assuming that a person is just inside their claims. When it comes to using tridents to fish people out of claims, that is merely taking advantage of a vanilla aspect of a minecraft game, which is riptide in tridents. Instead of banning this action altogether, all you need to do is go to a safe place, like a house or a closed perimeter, and make sure to tp or go somewhere else. These type of actions actually make players more aware of their surroundings and allow them to consciously understand that they are at risk from not a glitch, but from something vanilla in the game (aka a trident, that’s already hard to get). If a person has the funds to purchase a trident, then uses a vanilla enchantment to use in game, then you don’t have a problem with the action, you have a problem with the game of minecraft itself. Instead of banning this action, banning those items will be a much more viable solution because there would be no reason to have a trident in game if you don’t have riptide (I know MULTIPLE people I can list who had tridents and each of them prefer riptide on a trident apart from anything else). By taking away this item, the only way to actually fish people out of claims will be people who are next to pvp areas, and they should know they are at risk because being a part of a battle means you are taking a risk of fighting and losing your stuff. If you aren’t willing to fight, then don’t come to a battle OR be in a distance where fishing isn’t possible. Also, for the trident fish tactic, deleting all tridents in game will be better as so there wouldn’t be tickets where an admin or Fix will have to look over and bypass a moderator’s decision because they never took part in a pvp battle or don’t understand how to take advantage of vanilla minecraft items in battle, such as using riptide while being in water. All in all, it is better to ban tridents altogether than it is to ban that kind of fishing because you don’t have a problem with fishing people out of claims (as in the edge of a wilderness chunk), you have a problem with people being fished while deep in claims (i.e. using a riptide trident by either using /pweather OR by finding a water block). 

Edit: forgot to finish the last sentence

**Comment by KarlOfDuty** [comment]
Using fishing rods on players in pvp-disabled claims is disabled in towny but it is glitched on our server so it doesn't work, it should thus count as an exploit. Using fishing rods when both players are in pvp enabled areas however is allowed.
