### ISSUE TITLE
Rule Complaint, Interpretation and Definitions Rule 1.3

### ISSUE THREAD

**Issue by ghost** [EarthMC/EarthMC.net#16]

**Comment by Aitonater** [comment]
Just to clarify I am not wanting people to weigh in on the situation that gave rise to the contradictory statements what I would like to know is:
If using exploits like enderpearls, boats and entities to gain access to otherwise inaccessible places are not exploits the rule refers to, what kind of exploits are? 
Futhermore, what is a "minecraft issue" and a "server issue"? What is the difference and why does it matter when applying rule 1.3? Rule 1.3 does not state or disclose for example: "this rule only applies to server issues"...

**Comment by Aitonater** [comment]
Another quote from a mod on the rule: "I think the staff agrees that popular MC bug/Exploits are fine."

**Comment by Aitonater** [comment]
Mod: "***** said they are MC exploits. We do not allow server exploits." Ok very confusing so there are some Minecraft exploits that are allowed but server exploits are not allowed. I am still unsure of the difference and Rule 1.3 makes no mention of this anywhere...
