### ISSUE TITLE
[Rule Change] Rule 3.3

### ISSUE THREAD

**Issue by MarkusAurelius124** [EarthMC/EarthMC.net#166]
To whom it may concern,
After seeing the new changes to Rule 3.3 regarding Claim-blocking, I must say it just looks like a blatant throwing away of staff's responsibilities. I understand that tickets must have been opened repeatedly and staff had to deal daily with probably dozens (or hundreds) of them, but this new rule seems, at first glance, absurd. It allows the Tentacle claiming style of blocking a town, which would not only create ridiculous towns but also cuck towns that wanted to expand in specific areas. It doesn't discuss Swarm blocking (When a nation creates a swarm of towns around the target), nor towns that are already surrounded on 2/4 by either Ocean, or other towns.
I'm not saying towns won't eventually be unable to expand due to the development of the region, but just allowing to block 2/4 of them is absurd.

Edit: A possible solution to the situation would be to revert and examine each case individually. Yes, it's at times very demanding of both manpower and time, and I understand the desire for a specific rule for all to abide by, but in this case too many players would fall between the cracks for it to be justified. If needed, recruit more moderators, or even assign a specific task force to deal with claim-blocking issues.
I'll be more than glad to spearhead such efforts if necessary or even take part in them.

**Comment by DeadGlamour** [comment]
Lol look on Jerusalem, they cant expand now, this new rule is way too exploitable and will just lead to more toxicity and claimblocks.

**Comment by MarkusAurelius124** [comment]
> “With the right approach to handling claimblocking tickets, no matter how difficult they are, a ticket would take, at most, a week to close.” Im glad you have an opinion about this issue but you haven’t suggested an actual suggestion, what is the right approach that we aren’t already doing? What is the level of specificity that you would consider it to be less generalized but generalized enough to work for everyone and not too specific that people find ways to circumvent the rule?

My apologies. English isn't my first language, it seems I've gotten something mixed. In the previous post, when I wrote "Too general" I was mistaken, the correct phrase would be "Too specific". As in, it's too specific because it doesn't address other forms of claimblocking.
It's the other way around. The current rule specifically serves players in cases where claim blocking is obvious (3/4).
I gave many suggestions. For starters, go back to the old rule, or make this one more general. Off the top of my head -

1. "Purposefully and maliciously blocking off other towns using claims is illegal. Mayors are advised to mediate among themselves. Should that be impossible, it would be left to staff's discretion."

1a. The result of this would an expanded amount of claimblocking tickets, yes. To that end, my suggestions would be:
   A) Hire more moderators to handle he influx of tickets.
   B) In the legal field there's a term called 'Preliminary Hearing'. It's the stage when, before proceeding to trial, a judge must
       decide if there's enough evidence to charge the person with a crime. In this case, a person who opened a ticket would need 
       to provide enough evidence to justify advancing it to the next stage. The moderator in charge of filtering quickly looks over
       the charges and evidence, advances it if needed, and if not, explains why and closes the ticket.
       Basically, a better, more efficient filtering system.
    C) And when all else fails, even if the process will take time, even if there will be many tickets and not enough moderators -
        At least players will know that their problems would be eventually addressed, and not just give up immediately.

2. Alternatively, keep the current rule, but add common forms of claimblocking to it - Swarm blocking, Ocean Blocking, Tentacle Blocking etc. Basically, change it in a way that preserves the spirit of "3/4", but still gives players options for aid.
Ex: "Blocking 3/4 of a town is considered illegal. Other forms of claimblocking will be determined by staff's discretion."
I understand this might seem too general, but keep in mind that even though Murder isn't legal, there is still a variety of different situations and cases that the courts handle every day regarding murder, not all with the same result.

3. After you improve the filtering system, make the ticket system more efficient:
  A) Improve coordination between the moderators, I've witnessed myself one moderator's decision being overthrown by 
      another because the two had no knowledge of each other's cases. Put an organizational system in place to keep ticket 
      rulings into an archive moderators can access, where they can at most, view old tickets details, or at least, the names of
      ticket openers and the moderators in charge of them. That way moderators in charge of both tickets and filtering will
      have an easier time handling them.
    B) If needed, create a script for handling tickets. I myself was in a ticket that lasted months where multiple players were added
     to it, while the ticket itself was just about one town blocking another. There should be only three people in a claimblocking
     ticket - The Moderator, Mayor A and Mayor B. Place time limits - If a ticket is opened and the Offender doesn't respond after
     an amount of time, the ticket goes to the Victim. If the Victim doesn't respond after an amount of time, the ticket is dropped.
     C) And again, I cannot stress this enough - IMPROVE COORDINATION BETWEEN MODERATORS. There should not be a
     situation where a player goes "This moderator is slow, this one is fast, this one cares more/less than others, Ill open a new
     ticket so a better moderator will decide". Create or improve the set of guidelines for moderators to follow when 
     handling/filtering tickets, or a script for them to follow if needed.

This is a rough draft of things, if necessary I can work with staff to form a script and/or set of guidelines.
Also, as I am no moderator I can only comment using personal experience and understanding of the situation, if I had the actual "guidebook" Moderators are given I'd be able to offer more specific suggestions and changes.

**Comment by Semisol** [comment]
This screwed me over a long time ago, while having ownership of a town and the ticket being left open for a month or so, then just being closed with "your town seems like a claimblock", while the other town was literally intruding into mine and my claim was just made by the previous owner of the town and possibly was an incomplete build region.
This rule creates a lot of things that can be exploited, and I have to say this, **EMC staff are corrupt and accept changes without thinking about the consequences.** (remove this part if you like but, that will just most probably be censorship.)

We need a detailed rule, not 75% of the town or other stuff. We need to take in count good faith claims that were created for expansion and claims that have been made for ruining the experience for others or preventing other towns from expanding intentionally.

And people are abusing this. We need a solution. We need a system to make exceptions to rules, where if it was a mistake it would just be reverted while an intentional action done to damage someone else that is not 100% covered by the rules (such as, the 75% rule) can be punished.

**Comment by Semisol** [comment]
> “we shouldnt just destroy the fun for players entirely, as some towns cant expand thus play“
I havnt expanded any in about 6months. I hardly have a large town as well and used to be number one on top playtime. If you want to you can make a town in an area that is not crowded already and expand as much as you want like by the new world spawn. Fighting is about strategy and not really just killing someone and taking their stuff.

The problem is, the land is lost forever and there is no way to get it back.

EDIT: wrong quote

**Comment by Semisol** [comment]
Yeah, issues like this get slipped under the rug. It has been 16 days and no one even responded.
EMC staff are corrupt. Thats all I have to say.

**Comment by coblobster2** [comment]
and mods tell me the problems are not with the rules. Well, it is either the mods or the rules. I think it is both. Mods never seem to be on the same page so they disagree. Ok, that makes sense but when it comes modding they need to come to a good conclusion. I get making claimblocking legal to an extent. I think the main problem with this rule change is that it was very sudden so people were not able to prepare. We have seen this happen with other stuff such as the mapart rule, fishing rod exploit, and nation names rule being suddenly enforced (yes this last one is not a big deal cause they don't get warned but people lose gold). Not allowing time for people to prepare puts some people into a sudden advantage which is okay eventually but if it gives someone an immediate advantage then it is an issue. It is almost as if an admin went on the server one day and said if you have 30 fix books you get a 3k gold. People would not be happy because they did not know ahead of time to keep the fix books. I am not sure what extent to allow claimblocking cause it kind of depends on the location but this rule does seem to not outlaw enough that people pointed out above. The worst part is that this rule was made on here and people seemed to be happy with it but since it was on github where no one looks the community is now mad. please make a forum.

**Comment by coblobster2** [comment]
I would love if more people tried making treaties but the truth is there are younger, older, trolls, and toxic people who just won't be able to. Some areas of the world do this like where I am but even some of those were some of my least favorite days on EMC. Had insults flying, shouting wars, and countless arguments with people over borders and they were not even my borders. Borders are always a problem on EMC and expecting everyone to make a treaty just does not seem like a feasible response. I think this could be another job for helpers. help create border agreements.

**Comment by Barbay1** [comment]
**Proposal how to deal with new town built inside a hollow claim**
If the rules changed so that hollow claims are not allowed, another town shouldn't be allowed, because then they can claim that they've being claimblocked.   
1) We should give the surrounding town mayor some time (1 week per chunk, depending on the number of chunks) to fix the hollow claim.  
2) As for the little town ... it needs to be refunded and deleted, until the time is up and the surrounding town mayor either fixes the hollow claim or rearranges his chunks
3) Mods should be able to help the surrounding town mayor rearrange his chunks.

**Comment by Barbay1** [comment]
Proposed changes to 3.3 Claimblocking 
**Hollow claims on a lake**
A town that surrounds a lake (or large body of water) is not required to claim the lake, because of our terraforming rules (i.e. they can't build on the water that much).

**Comment by DeadGlamour** [comment]
> **Proposal how to deal with new town built inside a hollow claim**
> If the rules changed so that hollow claims are not allowed, another town shouldn't be allowed, because then they can claim that they've being claimblocked.
> 
> 1. We should give the surrounding town mayor some time (1 week per chunk, depending on the number of chunks) to fix the hollow claim.
> 2. As for the little town ... it needs to be refunded and deleted, until the time is up and the surrounding town mayor either fixes the hollow claim or rearranges his chunks
> 3. Mods should be able to help the surrounding town mayor rearrange his chunks.

**Comment by DeadGlamour** [comment]
> **Proposal how to deal with new town built inside a hollow claim**
> If the rules changed so that hollow claims are not allowed, another town shouldn't be allowed, because then they can claim that they've being claimblocked.
> 
> 1. We should give the surrounding town mayor some time (1 week per chunk, depending on the number of chunks) to fix the hollow claim.
> 2. As for the little town ... it needs to be refunded and deleted, until the time is up and the surrounding town mayor either fixes the hollow claim or rearranges his chunks
> 3. Mods should be able to help the surrounding town mayor rearrange his chunks.

I personally dont see the need for this, rules already forbid hollow claiming and if some1 hollow claims a large area they should just have the area removed.



> Proposed changes to 3.3 Claimblocking
> **Hollow claims on a lake**
> A town that surrounds a lake (or large body of water) is not required to claim the lake, because of our terraforming rules (i.e. they can't build on the water that much).

Absolutly agree,  towns around bodies of water shouldnt be bothered to claim massive areas of useless waters you cant build in nor does any1 want.

Also sorry for the double posting (1 got deleted), I inmistake pressed comment before finishing.

**Comment by Barbay1** [comment]
The problem with a town inside a town is ...
1) It's just recent that hollow claims are visible
2) I think the town should have a week or so readjust its chunks, because it may require a mod's help
3) I've been told last year that marking out your territory before you have enough gold to claim all of the land is ok, because it's planned expansion.  Of course things may change now because of newer hollow claims rules.
4) Even though it's a hollow claim, it's kind of rude to build inside one, because of (3) above.

**Comment by MarkusAurelius124** [comment]
So is this thread as dead as EMC?

**Comment by Colt44Magnum** [comment]
> So is this thread as dead as EMC?

Yes, though at one point I thought I remember seeing Karl push an update to this rule on the old website but its not on the new one so I don't know if it actually was updated. Seems we will be stuck with the good ol 3/4 rule until more people complain. The two nations that were the epicenter of getting this rule changed back are both now as dead as a door knob

**Comment by Semisol** [comment]
> So is this thread as dead as EMC?

more dead than emc.



> > So is this thread as dead as EMC?
> 
> Yes, though at one point I thought I remember seeing Karl push an update to this rule on the old website but its not on the new one so I don't know if it actually was updated. Seems we will be stuck with the good ol 3/4 rule until more people complain. The two nations that were the epicenter of getting this rule changed back are both now as dead as a door knob

ok
