### ISSUE TITLE
3.3 Revision (Reposted Since Incorrect Page)

### ISSUE THREAD

**Issue by Neowyld** [EarthMC/EarthMC.net#170]
Current Text: 

> 3.3 Town claims
Towns are not allowed to have areas of unclaimed chunks inside of their borders as this can substantially increase the size of a town without them actually having to increase their claim limit legitimately. Surrounding other towns with claims is also not allowed, about 3/4 of the town has to be surrounded for it to count as illegal. The only exception to this is when a town is created in an area where it is already surrounded.

Proposed Text:

> 3.3 Town Claims
Towns are not allowed to have areas of unclaimed chunks inside of their borders as this can substantially increase the size of a town without them actually having to increase their claim limit legitimately. Surrounding other towns with claims is also not allowed, about 3/4 of the town has to be surrounded for it to count as illegal. The only exception to this is when a town created in an area where it is already surrounded. **Additionally, claim arms which extend beyond a "natural border" by two chunks or more must be at least three chunks wide consistently.**

Many people have called for a revision to 3.3, and some have even said to revert it to the old rule. The iteration of the rule I am proposing will dissuade claim blocking in a severe financial way without staff intervention. It makes it so that it costs 48g per length to arm toward or across another town. It will also encourage more "natural-looking" borders instead of the spaghetti bordergore we are getting currently. 

One thing the current claim rule did was relieve a lot of unnecessary work for the staff team. Claim blocking should be a geopolitical issue, not a staff issue. Extreme cases should be dealt with, but my iteration of the rule would make enforcement easier than enforcing the hollow claim portion of the rule, meaning less tickets and less time a ticket is open of that category. 

The old rule should not make a return because it flooded the claim blocking category with issues the staff team simply should not be dealing with. Borders should be allowed to touch if done so in a natural way. There were so many cases of people simply expanding and the "victim" would make a ticket. Then the mod would have to be a third party in border agreements. Those tickets would be left opened forever, and the mods assigned would have to keep track of every agreement. It was far too impractical. 

I would suggest that players be given about two weeks of preparation to either widen their claims, or submit tickets for refunds if this new rule were to go into effect. 

Discussion can be made about the proposed width and the length which a claim arm starts and what constitutes a "natural border."

**Comment by DeadGlamour** [comment]
This still doesnt solve towns getting blocked by 2 towns or more, using the sea to not pass the 75% rule, nor does it solve nations making new towns in small areas purely to annoy/hurt another nation, while ye its def good progress it doesnt solve the biggest problem, which is :
Towns can easily get blocked and have 1 of the most important gameplay part removed (that is exapnding).
And to everyone saying, they can just keep playing they dont have to expand, there have been cases of towns getting 100% claimblocked and never to play again because of that, and I have seen people actively calling to use this steategy (claimblocking) to get people to quit, since its just that effective.
P.S
I find it funny they didnt add a war plugin for years, because its not good for peaceful towns yet they make this rule, which is way worse, I am well aware staff have had many tickets and its annoying af, but simply allowing this is also not a good solution.

**Comment by Mikeyreza** [comment]
> This still doesnt solve towns getting blocked by 2 towns or more, using the sea to not pass the 75% rule, nor does it solve nations making new towns in small areas purely to annoy/hurt another nation, while ye its def good progress it doesnt solve the biggest problem, which is :
> Towns can easily get blocked and have 1 of the most important gameplay part removed (that is exapnding).
> And to everyone saying, they can just keep playing they dont have to expand, there have been cases of towns getting 100% claimblocked and never to play again because of that, and I have seen people actively calling to use this steategy (claimblocking) to get people to quit, since its just that effective.
> P.S
> I find it funny they didnt add a war plugin for years, because its not good for peaceful towns yet they make this rule, which is way worse, I am well aware staff have had many tickets and its annoying af, but simply allowing this is also not a good solution.

I do agree with you that its complete BS nations can get around the 3/4 role by making multiple towns, but "nations making new towns in small areas purely to annoy/hurt another nation" isnt a problem. Thats literally what planting a town is, your goal is to get the other nation to surrender to you by annoying them and hurting their nation.

In my opinion, 2 chunks out is way too little space to expand without having to spend 3 times the amount of gold you would normally if you were just making a normal arm. I think around 5-10 would be much better since its difficult to just fully claimblock a town when you can only expand 10 chunks towards it unless that town is very small.

**Comment by coblobster2** [comment]
As much as I think claim wars would be fun. I do not think it is the best for emc because there are people of all ages and different levels of toxicity causing it sometimes impossible to make a border agreement. I think at this point reverting back to the old rule would be best. If they ever add helpers to the server this is something they can take care of.

**Comment by DeadGlamour** [comment]
When I say make a new town in small areas I mean making towns between towns or very small closed areas ment for claiming (cough ughbraces).
And ye 10 chunks wide or so would be great, and while it doesnt perfectly fix it, its certainally better than the hell it is rn.
I am also happy to see there is an agreement nations shouodnt bypass the 75% rule, even if I dont see concrete ways to prevent it.

Nontheless, I do have to point out a few problems I see:
1. A town could save up the gold for a while, keeping seemingly good relations, then claimblock an entire town with the gold at once, so it might delay complete claim blockings but it wont prevent them.
2. It forbids defensive claim arms, that to say claim arms ment to protect the town rather than completely block expansion of another's town, this destroys 1 of the last ways to defend claims, thus increasing the core problem with the new rule change, which I didnt mention here so:
In the new rule, you have 2 general ways of acting, block or not block, if you claimblock, you insta win and get everything, if you dont block you get nothing and might get blocked first, thus losing every chance to expand, by forbidding arms and hollow claims, it effectively prevents all kinds of defences from claimblocking, making your only option to block first (negotiations arent always that tempting sibce half the server are toxic af), this furthers promotes to the problems and causes players to become even more toxic and claimblock even more.

**Comment by FutureLemon** [comment]
Right page x) 

Without a war plugin or any other form of taking over land any form of claimblocking can simply not be allowed. The reason why it cannot be allowed is because a claimwar ends with people quitting 100% of the time I can very much confirm this. And given EMC's current fragile state you really shouldn't take the risk of losing any players old or new. Perhaps you are very correct about the amount of work it takes for a mod to figure out the actual claimblocking but that is IMO on the mod their side with lack of active toggled support staff and experienced staff. I can't think of more than 5 moderators who actually have had first hand experiences with claimblock.

**Comment by shirazmatas** [comment]
Follow format and reopen
