### ISSUE TITLE
1.1 Cheat clients and other modifications

### ISSUE THREAD

**Issue by FutureLemon** [EarthMC/EarthMC.net#184]
**Exact wording of the rule**
1.1 Cheat clients and other modifications
Cheat clients, macro keys and other modifications which give the player gameplay leverage over other players are not allowed. Players found breaking this rule will face a permanent ban, and yes, permanent means permanent.

Currently as stated above that is how the rule is as of right now. This makes it so even small offences like having your minimap toggled to show entities or a health mod that exposes invisible players  will get you permanently banned. This is rather strange since these are minor offences and barely even listened to resulting in an unban and nothing more. To counter this issue of people getting unbanned without any consequences at all I have written a new rule and thought it might help.

1.1 Cheat clients and other modifications
Cheat clients, macro keys and other modifications which give the player gameplay leverage over other players are not allowed. For more serious offenses like cheating, offenders would face a permanent ban.

**How will this rule affect the community**
This will affect the community positively because moderators who permanently ban others for minor offences often get heavy amounts of criticism even though they simply followed the rule. 

**Do you think this will benefit both the staff and the players**
It will make staff jobs easier to deal with less appeals for every person who gets banned for having entities enabled on their minimap and could instead just receive a warning instead. In the same way it will also benefit the players by not losing time with unnecessary appeals being unable to play the server.

**Comment by Pengun78** [comment]
Je bent gebanned

**Comment by jwkerr** [comment]
I personally haven't seen any examples of someone getting banned for minor modifications like that but the rule does make it seem like that's possible and if it has I definitely agree with this change.

**Comment by FutureLemon** [comment]
> I personally haven't seen any examples of someone getting banned for minor modifications like that but the rule does make it seem like that's possible and if it has I definitely agree with this change.

Kilomberox was permbanned half an hour ago for having a hp bar mod that also showed invis players and he's most likely getting unbanned

**Comment by Nikocholas** [comment]
As Kilomberox, the victim of this ban, I have to roundly agree. It's pretty shocking to see how popular people are banned for doxxing and unbanned after 1 day and I was just PERMANENTLY banned for using a health indicator (the only one that worked with my minimap and optifine mods) that had a function which I never seen before... I hope I could get unbanned, been playing since 2018 Christmas.

**Comment by FBI-Bro** [comment]
I agree with this. It just makes sense.

**Comment by RoseBrugs** [comment]
I agree with the suggestion, the wording could use reworked.

**Comment by shirazmatas** [comment]
instead of 

> 1.1 Cheat clients and other modifications
Cheat clients, macro keys and other modifications which give the player gameplay leverage over other players are not allowed. For more serious offenses like cheating, offenders would face a permanent ban.

have
>1.1 Cheat clients and other modifications
Cheat clients, macro keys and other modifications which give the player gameplay leverage over other players are not allowed. For more serious offenses like cheating, offenders will face a permanent ban.
