### ISSUE TITLE
Proposing a Limit to Profits (and Limit of Loss) due to a Scam

### ISSUE THREAD

**Issue by Barbay1** [EarthMC/EarthMC.net#191]
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
There are too many incidences of players losing hundreds of gold ingots when buying or selling nations.   For players who have invested a lot of time in getting enough gold, or building up a nation, this is unacceptable.

There should be a limit how much one can get scammed -- about 100g is fair. That'll be about 1/2 to 1 month worth of voting every day to recover that loss.  The remainder should be removed from the scammer and returned to the original owner.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
**Exact wording of the rule**
Rule x.x Scamming

While scamming is legal, there is a limit how much a player may profit from a scam.  The limit is now 100g.  Players who lost more than 100g in a (town, nation, or expensive item) scam may ask for staff assistance.  The first 100g goes to the scammer.  The balance of the amount will be deducted from the scammer and returned to the player. 
For example, a scam of 530g will result in 100g to the scammer and 430g returned to the player.

To get a refund, you must provide evidence to support your claim:
1) in game name of the scammer
2) proof of payment (screenshot or video)
3) proof of scamming (screenshot or video)
4) date and time when it happened 
5) must report the scam immediately/ASAP so that the claim can be verified

**How will this rule affect the community**
While people should learn to be careful in transactions, loss of half a years worth of work is not acceptable. 
Scammers still have freedom to profit from scams, but victims will have a limit to their losses.
A reduction in toxicity overall.

**Do you think this will benefit both the staff and the players**
This rule allows freedom to scam, while protecting the victims so that they can recover.
Players collect and provide the evidence to make the job easier for staff.
Clear rules make dealing with scams more uniform.

**Please use <https://github.com/EarthMC/Issue-Tracker> for issues other than the EarthMC.net website**

**Comment by jwkerr** [comment]
A large selling point of EMC is its player run economy (it is listed on the main page of https://earthmc.net), server/staff regulation of trade in any way in my opinion and likely other's would be very detrimental to the server. There are communities such as EMC Scams that inform players about who and where to safely trade with that are ran by players to combat scammers just for this reason. 

A few more problems include:
What happens if the player who committed the scam does not have the gold anymore? Where will that gold come from? you can't just deduct gold from someone's balance if they have already spent it.

Scammers would likely just move to dealing in solely items and again it is a player run economy, the staff can't just decide what an item's value is to counteract this.

If this rule were to be imposed, even if evidence collection is done by players to make the job easier for staff that is still a job they have to do, i.e. verify authenticity of the evidence, provide item refunds, verify how much was taken. The time spent on this could be much better spent elsewhere where the community really wants change. 

Also side note, who is losing half a years worth of work from one scam?

**Comment by Bigious** [comment]
Bruh this shit is dumb. EMC has already added a lot of ways to not get scammed like tf? You can't spawn trap, you can't lure, and they even added /trade oh yeah and chest shops. The way that's easy to get scammed is buying nations and towns, but why propose a rule change for those types of scams? Just add a function to sell nations and towns. At this point, if you're getting scammed in EMC with all the resources then that's kinda your fault. Not to mention all the complications with evaluating items and just the logistics of refunding someone.

**Comment by Xyronius** [comment]
It's hard to get scammed on EMC, as Bigious has said you got the anti spawn trap rules, you can't fish anyone out of claims, you got /trade and chest shops. Also if there's a scammer most of the playerbase knows their name due to the one being scammed notifying everyone or the EMC scams discord server. Scamming has been allowed since the beginning (correct me if i'm wrong) and there has already been done a lot to make it easier for the players to not get scammed because let's be real, most of the players that are scammed are new and will learn from it. It's another step in your EMC development and it also helps you with your trading manners. It'd be too easy for the players to just get most of your gold back while you made the mistake because you can easily prevent yourself from being scammed like going to a neutral place, asking if the person is safe to trade with, check if the prices are somewhat realistic and more.

**Comment by BreachDGates** [comment]
I disagree with Barbay, well it’s very hard to get scammed. If you want to buy items you can ask to trade in a safe place, if the scammer denies, don’t trade. Join EMC Scams discord, get experience, read the chat and check who could be a potential scammer. Remember their names. The more you play, the more you will understand who you should trust.
Feels bad for the new players who don’t know about this threat. If they get scammed they will learn from their mistake and some will never get scammed again. Obviously I don’t encourage scamming, but be aware.

There is no need to make a ticket if you get scammed. This can only increase the amount of work that a staff needs. You can get 100g in approximately 1 hour of mining, don’t waste this time on making a ticket because it would take a long time to get a response. So many steps to follow in order to get a mere 100g refund.
