### ISSUE TITLE
New rules according to a gameplay and playing politics/diplomatics

### ISSUE THREAD

**Issue by 3meraldK** [EarthMC/EarthMC.net#196]
**Exact wording of the rule**
2.12. Ruining the concept of doing politics is prohibited. Behaviors such as:
- logging in each few weeks within a long period of time (judged by staff) just to keep your town. In this case, a mayor account can be purged. (if registered few times)
- keeping your national high rank (for an instance a king) and your nation in an inactive status, not allowing other nations to expand properly and become active again in this region.
- saying your political enemies while being inactive (read subsection first for an instance) that giving them town is impossible whilst having a stupid reason for that. It's a clear act of prohibited trolling and is not tolerable.

These things are not allowed, unless you have a very good reason for that. You are allowed to troll in any kind but not most of the time (which will be judged by server staff). 

**Rule 2.12. can be used only, when a nation is in an ongoing conflict. (but it's discussable)**

**How will this rule affect the community**
I was experiencing that few times. Firstly, it started in Summer 2020. Guess, where I lived back then. In the one of the most inactive places in Europe, Poland. Except of allowing neighbors successfully make their ambitions done and players actually enjoying gameplay of real politics (on this server, so-called "Geo-politic server", I saw Polish government (for an instance, of course) and Polish mayors keeping their towns just to keep them. It's very stupid and ruins the concept of EMC. 
Even as CorruptedGreed said, the portion of trolls on EMC is large. Nobody likes trolls, right? Trolls ruin games, that can be a real menace for the future of the server. It would be rather "build your town in an unclaimed area" (for Europe its nearly impossible to find a new one) or "Wanted to have national ambitions? Sorry, but it's impossible here, we keep inactive players even for a year or more." Now, still playing in 2021 January I am suffering this. Just look how 10-13 polish mayors are logging in every month. Even asked a Wroclaw's mayor to give up his town and let Germany expand. His answer was "No, I won't, It's funny to see German people annoyed". Then asked why he plays EMC. "I join there because I want to annoy Germans" (if  you want proof, DM me 3meraldK#3099). And so on..

**Do you think this will benefit both the staff and the players**
It will surely benefit all the players. Not only decreased numbers of reports, but largely reduced acts of trolling, which will make this server's community more perfect. That will be why many old players will return to their homelands and start playing actively again. I see a lot of benetifs caused by working with those rules. Nations with their expanding ambitions, or just countries which have a ongoing conflict, but couldn't continue due to enemy's inactivity, can enjoy their game now. It will not just be "build towns in EMC" but "play geo-political server called EMC, build towns, nations and civilizations".

**Comment by 10op10** [comment]
I have been wanting something like this since I joined EMC, The worst thing is towns being held by alts/inactives or trolls and it is really annoying

**Comment by geobeeblaster** [comment]
No, first of all this rule is extremely interventionist, allowing mods to delete towns based on discord politics, despite the protests of the mayor. The integrity of a town should be decided by that town's mayor alone. Imagine if you joined this server, spent time building a town, and then quit, but decided to log on every month to save your town. Then, one day, you log on to find your town greifed due to expansionist neighbors using discord politics. Not everyone is on this server to engage in roleplay and assuming that as a fatal mistake. This server needs less rules, not more.

**Comment by DeadGlamour** [comment]
Amazing rule, yes let's let moderators, who are mostly players and often high ranking / leaders, choose who should be removed purely on a subjective matter, such as activity, I am sure it will lead to no problems at all!

**Comment by Ionao** [comment]
The problem that for some respectful leader it is the only way they have for keep there nation alive and not being reduce to a 1 town nation and not being able to develop his nation again because of big nation like Oh Idk ... Japan ? it would kill all the charm of EMC as it would allow only the big nation to stay alive. It is the base of EMC tell me if I'm wrong to have multiple nation and to develop his nation but for some people due to not having a priority pass or premium + School/Work they can always be here and so forced to be inactive and I guess those people would get there town deleted if this rule were passing.

**Comment by americanfrog** [comment]
just shorten the 42-day timer. It would force people to log on more actively. And if you don't log on then too bad so sad. Things change.

**Comment by gabeeebaby** [comment]
Shortening the timer or making a rule wouldn't stopped it. They would just log on more frequently, without playing the game at all. Instead, adding town upkeep would be a better solution. This allows people who are active to take a break without worrying about their town/nation falling, by just grinding gold before hand. A two gold a day upkeep would be easy for any player to pay just through voting, but difficult for "42 dayers"

**Comment by Twitchyyy** [comment]
emc doesnt change/add stuff though lol
