### ISSUE TITLE
                                    Revised ban system-suggestion

### ISSUE THREAD

**Issue by L-Dazz** [EarthMC/EarthMC.net#37]

**Comment by WhitPlayzYT** [comment]
i personally think there should be a full emc forum for ban appeals staff apps suggestions bug reports ect ect

**Comment by watergod1234** [comment]
> i personally think there should be a full emc forum for ban appeals staff apps suggestions bug reports ect ect

This exactly. With tickety being broken it’s very hard to report issues, you have to personally message a mod and hope he replies.

**Comment by L-Dazz** [comment]
thanks for all the support guys! sorry for really bad formatting and some grammar errors tho

**Comment by L-Dazz** [comment]
oops what

**Comment by L-Dazz** [comment]
thanks for the support guys!

**Comment by FutureCW** [comment]
Along with the fact that discord doesn't allow users under 13 and there's people who don't have discord or aren't allowed to get it. Having an appeals forum on earthmc.net would definitely be beneficial

**Comment by Kyoris** [comment]
>the fact that discord doesn't allow users under 13

about that recent influx of discord members... *cough*
(*yes off topic but wc*)

**Comment by ghost** [comment]
We have a warning system for a reason. You get a temporary ban after you get your 3rd warning and permanently banned after 5 warnings. But for players with Cheat Client, we have had many players damaging the community with Cheat Client before. Just for an example, someone with XRAY can damage the community significantly. Hence the rule what we have right now against cheat client, i.e no tolerance for cheat client. Because you can not be sure if the player who cheated didn't have other hacks installed as well along with the one he/she got banned for. We have had players who continued to use hacks even after getting unbanned at the early days of EMC.

Players who get banned after 5th warning, we do usually give them a second chance, unless your case is really severe.

About Discord, it is a much better solution than the old forum we had. For example, discord allows us to check the history of the global chat easily, allows us to communicate with each other without needing another platform.

**Comment by L-Dazz** [comment]
i am aware that clients are a big deal but if you unban a hacker after his temp ban and monitor him it wouldnt be a problem, if he hacks again he can get perm banned its not going to kill the server, plus he will probably learn from his punishment and stop hacking.

**Comment by shirazmatas** [comment]
Potentially people could appeal through a gmail, twitter, or even facebook. Perhaps even reddit if they don't have discord

**Comment by L-Dazz** [comment]
> About Discord, it is a much better solution than the old forum we had. For example, discord allows us to check the history of the global chat easily, allows us to communicate with each other without needing another platform.

communication would not be an issue, if each appeal has its own number (or id) it would be easier to organize and archive them, further more communication from the server to the discord doesnt seem to be a problem. so why would communication from the website to the discord be an issue? what im basically saying here is that your point is invalid in terms of communication, i do understand that discord could be more convenient at times but a revised appeal system would do better in the long term, adding to that with the surge of new players it would be tougher to communicate through discord and not all players are over 13 or have access to social medias.

**Comment by ghost** [comment]
That would require having two individual platforms, which is a problem itself. Where we can simply use just a single platform to deal with ban appeals and other staff related stuff from one app, without having to maintain another platform. Also using Discord we have to worry less about the IT infrastructure.

But this platform was never the point of your issue. You want a revised ban system so that you can appeal again as well, as your previous appeal got denied. Correct me if I'm wrong.

Edit: So it's more like a rules issue, not the platform issue.

**Comment by L-Dazz** [comment]
> That would require having two individual platforms, which is a problem itself. Where we can simply use just a single platform to deal with ban appeals and other staff related stuff from one app, without having to maintain another platform. Also using Discord we have to worry less about the IT infrastructure.
> 
> But this platform was never the point of your issue. You want a revised ban system so that you can appeal again as well, as your previous appeal got denied. Correct me if I'm wrong.

well yes and no you did state the platform in your reply and i was just saying how a server based appeal system would infact be better and although it might take a few weeks to program (or months it depends) it would be beneficial to the server and the younger players. discord isnt the best option and although its useful and somewhat hassle free its not prefect and its not made for this kind of stuff, its also harder to archive and organize due to it being in its roots, a chatting program.  and no the platform is part of the issue having more control over the appeal system would be useful. and although i wanted a revised system so players have other options and are able to realize their mistakes and be beneficial to the community i also want it so newer players( and hackers) can help the server grow and prosper this server is an amazing idea and even if im never unabnned i wish to see it succeed.

**Comment by jawelman** [comment]
shiraz unban me dude

**Comment by L-Dazz** [comment]
> shiraz unban me dude

shut up dude

**Comment by jawelman** [comment]
> > shiraz unban me dude
> 
> shut up dude

You can stay banned smh.

**Comment by KarlOfDuty** [comment]
We will not be changing the ban system in the proposed ways.

**Comment by L-Dazz** [comment]
o
