### ISSUE TITLE
Towny plot scams/exploits.

### ISSUE THREAD

**Issue by KarlOfDuty** [EarthMC/EarthMC.net#64]
Hello everyone, I thought I'd open up discussion on the topic of rule enforcement on a specific issue: the towny plot cost scamming.

For those who are not aware, this scam has the buyer enter a plot which says it's for sale for a low price, usually 0, then the mayor of the town changes the price before the buyer purchases the plot. Towny only shows the updated price if the buyer steps out of and into the plot again so the new one is not known to them until they lose a lot of gold.

The question is whether to regard this as a scam, which is allowed, or an exploit of a towny issue, which is not allowed.

**Comment by ghost** [comment]
So basically combat-logging is an exploit.

**Comment by FutureCW** [comment]
It’s a scam. It’s not a glitch when the player being scammed still has control over the situation because they can still check the price whenever

**Comment by MikeOuO** [comment]
No. This is a bug abuse cuz that mayor exploits the town issue to get himself gold, which is not a proper way to get himself gold. And I suggest adding a reminder after the buyer did /plot claim, like "Are you sure to spend [amount]g to buy this plot?". Once this message is sent, the price of the plot cannot be changed. Then the buyer can do /plot claim confirm to confirm this purchase. Or /plot claim deny so that the mayor can set the price to the right price.
This issue is all about how u classify this issue. In my opinion, the mayor used the flaw of towny-- not showing the update of price after the price was changed once u are on the plot, to get himself gold.
P.S. I am one of the victims of this issue.

**Comment by MikeOuO** [comment]
> It’s a scam. It’s not a glitch when the player being scammed still has control over the situation because they can still check the price whenever

No. This exploit of the issue is that the mayor of the town do /plot fs [amount] before the buyer does /plot claim and after the buyer check the price. So when you are doing /plot claim. You won't be clued that the price was changed already.
So the timeline is like this:
Check price (which is often 0g)->Mayor do /plot fs [amount>0] (you won't have clue on that price change) -> Buyer does /plot claim (You expect the price is 0g but the actual price isn't)

**Comment by MikeOuO** [comment]
![圖片1](https://user-images.githubusercontent.com/53436441/62817973-5815cb80-bb72-11e9-8b21-caab1bc7e016.png)
Idk if this is achievable but this is a good way to solve this I guess. OuO/

**Comment by DeadGlamour** [comment]
I think you can also set a tax after he buys it and drain him

**Comment by JaVolimKatarinu** [comment]
I believe that this should be treated as an exploit from the Towny. 
As Mike said, he was the first victim of this ( to my knowledge) and he got "scammed" for 1k gold. The Mayor which "scammed" him created a new nation just a few hours later. This EXPLOIT allows them to generate awfully huge amounts of gold. If we just do daily voting, we need 100 days to collect 1k gold and somebody just takes them from you for a second. Especially when the reason that you were "scammed" was that they needed gold for their new nation. And the way you lost 100 days of vote gold is because there is a problem in code of, we all could agree, primary plugin of EMC...

**Comment by MikeOuO** [comment]
I guess I am not the only victim of this issue lel. As the Chancellor of that nation told me that the mayor "scammed" me had "scammed" people before with the same trick. And the mod in the discord ticket also said that I am not the only one to fall in this ploy.
So this issue should be solved as soon as possible to avoid more people falling into this trick.

**Comment by JaVolimKatarinu** [comment]
So we can assume that he earned 2k gold, at least. 2k gold earned from a "bug" in Towny plugin. I say that is an example of exploit abuse, not an example of scams. ;)

**Comment by MikeOuO** [comment]
Yea cuz after he "scammed" me, he created a nation. And like 2 days later, he were the king of another nation already.

**Comment by ghost** [comment]
I think this falls into scamming. When you buy a plot from someone just ask them not to stand on the plot at the same time as you. When we trade on EMC there is always an element of trust and a risk being taken. I feel like buying a plot where a mayor might attempt to suddenly change the price is no different. It's the responsibility of the player to have thier wits about them and be careful who they trust. Taking careful steps to prevent themselves being scammed. Like I said if you are worried ask the mayor to stand where you can see them before you claim the plot.

**Comment by FutureCW** [comment]
@MikeOuO I support your way to get around it where it asks if you're sure when buying a plot while also listing the price. It's still a scam when the player being scammed has the ability to just go in and out of the chunk right before doing the command.

**Comment by ghost** [comment]
Also to people in this thread. A scam and an exploit are not the same and scamming has always been legal. Dont cry when someone has gotten the better of you.

**Comment by MikeOuO** [comment]
Well, the point I was emphasising about is that there is a flaw in the /plot claim cuz there is a period of time that you can't confirm the price. And I had no intention to emphasis the living of the mayor afterwards. So please be focused on the classification of this case and go back to the right track.
I agree with the point that you can ask the mayor to stand on the different plots with you. But why should we accommodate ourself to the flaw of the server instead of the making the server improve?

**Comment by MikeOuO** [comment]
> Also to people in this thread. A scam and an exploit are not the same and scamming has always been legal. Dont cry when someone has gotten the better of you.

And I mean who doesn't know scam and exploits are different. And I am sure that everyone knows the difference. 
That's why we are discussing here classifying this case as a scam or an exploit... and also discussing if this should be considered as legal or illegal...

**Comment by ghost** [comment]
Mike the point is it's not a flaw. You want extra protection for something that works perfectly fine if you have a brain.

**Comment by JaVolimKatarinu** [comment]
No, it doesn't work perfectly fine. Whole Towny and plots don't work fine and need to be fixed. This isn't something major and required, but it would be better to have things like this work. And what I'm meaning is that, if you stand still in a plot and owner comes and changes any attribute of the plot, you would not be notified. Price, owner, PVP, mob spawns, everything that is tied to plot. No message in the chat, if you arent the executor of the command.

Isn't the point of programming to make our life easier? Why then should we ask Mayors every single time to step out of a plot so we can safely claim it by the price we arranged? 

Imagine it like shopping online. You go to Steam Store and pick yourself a few games which are all worth 15$. Great, you find the price fair and you proceed to buy it. You type in your credit card info and click to buy. And then, when you click to buy, Steam changes the price of your cart into 1500$ because you already gave info and they saw your balance. You pay 1500$ for 3 lousy games which are worth 15$, devs get parts of 15$ and rest goes in Gabens pocket. Do you find that fair and trustworthy? Do you see that as something legal to do? Does that make you come back and buy 5 more games? 

GitHub of EMC is quite unpopular, not many players actually come here and read the issues. Nor read all the potential info that it can give you. And they don't know about this. And what if 40% of all Frenches that are playing right now get this info? What if Fuze comes back and does shit like this? If this gets described as scamming and comes out as a legal thing, I don't think that many people will continue to play. Mayors will lose the trust of new players and the next thing you know, the map will be 100% claimed with 1 man town/nations. 

@Aitonater 
Actions have consequences and think about what could happen if this goes legal or illegal. Because from my point of view, setting it legal can only lead down, not up. It is your call, don't cry later when there is no one to play with you. ;)

**Comment by MikeOuO** [comment]
But the point is that the towny doesn't work fine, neither is the plot. It is ridiculous of you saying that it is not a flaw. And the point I was saying about is that why would you need extra protection if the towny works fine. If it is really fine, no one would have to do extra protection. If it is really perfect, why would the whole GitHub EarthMC exists...

**Comment by Samshaw0** [comment]
It’s an exploit of the game. It shouldn’t be allowed. Irl you know how much u buy things for so there shouldn’t be this in game

**Comment by KarlOfDuty** [comment]
It has been decided that as the price not being updated for the buyer is an issue in towny this will be classed as an exploit instead of a scam.

**Comment by MikeOuO** [comment]
Yea boi.

**Comment by ghost** [comment]
so if we do this now its breaking the rules? what are the punishments?

**Comment by MikeOuO** [comment]
Getting warned.
