### ISSUE TITLE
[Rule] Change 2.4 a very tiny bit

### ISSUE THREAD

**Issue by FutureCW** [EarthMC/EarthMC.net#71]
Just add the word excessive in front of every part of rule 2.4

**Comment by johnyuki** [comment]
I just had a long discussion about this with Eagle. He said that it is completely up to the moderator that is on at the time whether you get warned for something or not. So basically the rules are very vague and that not even the mods have clear boundaries for what is/isn't toxic, or vulgar, or offensive, etc. He said the rules are still being refined, but yeah, people are going to have to make-do with vague rules for a while until they can decide on boundaries for the rules.

**Comment by DasCodes** [comment]
Yes, it's up to the staff to punish the player, but I meant that in controversial cases, of course, you're gonna get punished for doing things like griefing, racial slurs, spam, etc. Most of the cases are unique, you can't really put a boundary and expect everything to work properly. Hence, it's also written on the rule that, toxicity is defined by the staffs on a case by case basis. And, for a community like EMC, you really can't put a boundary, cause players will always find a loophole in it, no matter how much you try to make it right.

Yes, this rule was never updated before, but due to the increasing amount of toxicity, harassment, we introduced this updated version of it. We may tweak, add, remove anything we may find suitable.

**Comment by DasCodes** [comment]
> Reminds me how I got warned for mute bypassing after weeks of bypassing while staff were online. Consistency is extremely necessary

Not every staff who is online in-game actively monitoring the chat or players, we have to check work on support tickets as well, which require us to alt tab out most of the time.

**Comment by DasCodes** [comment]
Yes, the new rule is more strict, but we had to update the rule due to the increasing amount of toxicity.

> it seems like you now are unable to insult anyone or harass them in any way

Well, player harassment is not something we are looking for in the community, which also drives players away from the community.

**Comment by DeadGlamour** [comment]
I would suggest considering scamming as toxicity, scamming is a really toxic thing to do, most people I know despise it and its really something that should be looked down upon

**Comment by KarlOfDuty** [comment]
I don't think this will actually make any difference.
