### ISSUE TITLE
[Rule] 2.1 Luring To Traps Shouldn't be allowed 

### ISSUE THREAD

**Issue by T0rn4do** [EarthMC/EarthMC.net#79]
Hey,
On the other day I was playing Emc like normally and a guy say in the chat :
"Im leaving this server and I give my stuff"
So I came to the nation spawn and followed him to a room where he was going to give me his stuff and all 
But another guy was next to it and activated a falling trap and I died with my god stuff on and lost around 100 golds for nothing.
So I looked the rules and it was allowed .
I was saying to myself why are Emc rules so unfair ...
Like luring players to die in some traps should be forbidden or only if the player is annoying someone so we can actually trap him like in youtubers case .
It would be better for players an update for rule 2.1
Thank you for reading this and to understand me 
T0rnado.

**Comment by Lagann311** [comment]
I agree. Got trapped like this 2 times as well

**Comment by T0rn4do** [comment]
I'll not give names for now but if mods need I can give them.

I'd like a refund tho

**Comment by maxifunseeker** [comment]
I agree

**Comment by DeadGlamour** [comment]
Nothing is fair, so please stop crying about it, many people tries to trap me, just keep an eye out and trust no 1

**Comment by WhitPlayzYT** [comment]
Just kill the spawn trappers like I do

**Comment by Bigious** [comment]
To clarify for people who believe a simple life isn’t fair or just kill the trappers. The way these traps are set up is to where you /n spawn into an inescapable hole and are immediately killed.this form of trapping shouldn’t be allowed because it simple is put is toxic. The way trapping should be allowed is the chunk in which u /n spawn into should be set to pvp protected at all times allowing players to escape but if a player risks leaving they are allowed to be killed this solves many problems!!!

**Comment by ghost** [comment]
i still say that nation spawn traps should be outlawed,

**Comment by ghost** [comment]
i have an advise:
put everything in your chest.
export all of your xp and put it in your chest too
then tp and you should b fine.

**Comment by ghost** [comment]
I don't agree with this. A reasonable player would take the necessary steps when meeting a new unfamiliar player.

Such as taking no items with them.
Only teleporting to nations and players that you trust.

Anyone who falls for these traps is being careless.

It is easy to avoid these traps you just need to exercise caution.

If a man says he has puppies in the back of his van and he turns out to be a child molester and kidnaps you it's sort of your own fault if hes a stranger and you didnt know him.

**Comment by SuperChrisBoy** [comment]
Spawn trapping/killing should never be allowed period.

**Comment by sgmedev** [comment]
# Is this rule change still being looked at or has it been abandoned
###### The last comment was in october last year
## AND IT IS STILL A PROBLEM

**Comment by KarlOfDuty** [comment]
Please follow the issue template.
