### ISSUE TITLE
[Rule] No Random Killing in towny server

### ISSUE THREAD

**Issue by maxifunseeker** [EarthMC/EarthMC.net#82]
**Exact wording of the rule**
Random killing means killing players in wilderness without facing aggression towards you or in a war battle. Noted that dual is not counted as random killing. Players who got random killed should provide evidence showing that you weren't being aggressive towards the player(s) who random killed you, examples of evidence include but not limit to screenshots of chat, video. Players who are found random killing others would receive a warning for the first time violation. Temp-ban for 3 days for the second time of violation. Recidivist who violates the rule for the third time will face a permanent ban from the server. 

**How will this rule affect the community**
As quite of the majority of the community are non pvpers, the rule would protect their game experience further. Note that this is not to deprive pvpers' right to pvp others, but to limit the situation that killing would be allowed in the towny server since random killing would cause disturbances to non pvpers and there's no difference between murdering in Minecraft and murdering in real life. For those who want to fight others without lots of restrictions, faction server is always a choice for them.

Also, if the rule was implemented,  there would be more astonishing creations from our community. It is because non-pvp builders can concentrate on what they want to build and the process of material gathering without worrying about being random killed by some random bloodthirsty pvper.

Some of you may argue that that's not necessary because those non pvpers can use invisible potions or hire a bodyguard to protect them. However, those things may not be an available option for all the players,  especially those who are relatively new and it causes injustice to those who have no access to those resources that can protect them and seriously damaging the gaming experience of them, and quitting the server will be a likely situation, which affect the player base of the community.

**Do you think this will benefit both the staff and the players**
For staff, applying this rule would help them to better fulfill their responsibilities to protect the gaming experience of players. Although it is foreseeable that there'll be lots of tickets about this in the beginning, which would increase the workload of staff, it will eventually drop when the community realizes that it is unacceptable to random killed. Also, applying this rule csn prevent situations like killing staff on duty, which would further protect the right and safety of staff when they are on duty.

As for players, like what mentioned above,  it can protect the gaming experience of non-pvp players from being ruined by random killing. This means the players who just want to build can concentrate on what they really want to do in this server. When they can enjoy this continuously, their gaming experience would improve, which is a great benefit for players.

**Please use <https://github.com/EarthMC/Issue-Tracker> for issues other than the EarthMC.net website**

**Comment by SnUncle** [comment]
Doubt it

**Comment by DeadGlamour** [comment]
That 1 of the worst ideas Ive seen in this server, it just ignores the server theme spirit and gameplay, I am not a fan of getting killed at the start of the game but that still fun, it adds a risk to the game

**Comment by Alexandre1868** [comment]
No, just no.

Why? 

Because you forgot to mention how there's another half of this server that is very PvP oriented. They kill people in wilderness, partake in wars, etc. 

This rule is most likely blatantly directed at many member nations of the Regional Powers, if not all, and we all know this. We don't go suggesting rules to "no claimhiding in towny server", otherwise all of Uesugi, Entente, and probably half of this server would be tempbanned.  If you wish to not be killed while building, claim your stuff, or take extra precautions to prevent yourself from being caught in the middle of PvP(check dynmap every so often, build with a group of friends, etc).

This is the most stupid and one-sided suggestion I've seen from my 13 months of playing on this server.

If you have even more reasoning on why this rule should not be implemented and is just out-right dumb, then comment and add onto this. (I made this in under 10 minutes so I'm probably missing out loads of info)

**Comment by 3meraldK** [comment]
hmmmmmmmmmmmmmmmmmmmmmmm no.
if you are pussy and u dont want to be killed just stay in your fricking city.
by wilderness many players can loot items but if you are weak just stay in your town as I said.
bye.

**Comment by GODTM** [comment]
shia your ideas are fucking stupid and should not  be added nor should you be staff

**Comment by WhitPlayzYT** [comment]
This is just dumb

**Comment by BommBap** [comment]
lmao pussy just stay in ur town,dont come out and fuck off
that stupid,we need more pvp than now and u say this hahah

**Comment by DeadGlamour** [comment]
Omg its bommbap, did yall know bommbap saved me from death and dukasv once (back on my ol username dune_walker)

**Comment by ghost** [comment]
The game can be played entirely without the need to leave unprotected areas. Making essentially the entire wilderness a protected area defeats the purpose of having towns for safety. The rule needing you to have some conflict with a player before attacking them is in itself a paradox. Conflict starts somewhere and it's often with an act of aggression or misunderstanding. If you in fact disallow this then you would end up in a situation where no one has a legitimate reason to attack anyone.

Yeah this is not a good idea and should never, ever be implemented.

It is the responsibility of reasonable players to take necessary precautions when they leave thier towns the onus cannot be on the server staff to police what would boil down into thousands of tickets with a "he said she said situation".

A reasonable player exercising the correct level of caution when leaving a town will successfully hide themselves on the dynamic map by using trees and cover. Pressing shift when they walk. Crafting invisibility potions which are now easy to come by because of mob spawning for spider eyes. Or even holding shift while they walk. In addition a player taking necessary steps will watch the dynamic map vigilantly while in the wilderness to watch anyone approaching them.

A player who has died in the wilderness to another player is being negligent to A. Not hide them selves and B. Not watch for the approach of other players (with the exception those other players may be invisible but referring to A. You should not be visible to them.

This should NEVER be a rule.
