### ISSUE TITLE
[Rule Suggestion] Rewriting of rule 2.1

### ISSUE THREAD

**Issue by ghost** [EarthMC/EarthMC.net#94]
As it stands rule 2.1 is confusing for both players and staff. The amount of times i can count having to tell players that trapping is allowed under certain conditions is just insane. I have taken the liberty of rewriting 2.1 to better fit the current meta of EMC.

"2.1 Trapping
The act of N/T Spawn trapping is forbidden as it ruins gameplay for many players. Traps that do not allow players to TP out of without death or intervention by a staff member are also forbidden. Traps that kill players outside of N/T spawns are allowed. If your are found to be using an illegal trap staff may issue warnings or even temp bans."

Feedback on this would be greatly appreciated

**Comment by ThundorLord** [comment]
I definitely agree that a change like this is needed. It's an abuse of the towny system.

**Comment by AmphireYT** [comment]
Yes I agree to with thunder

**Comment by ghost** [comment]
While I feel like its the responsibility of players to not trade or use nation spawns they are unfamiliar with. I do agree that changing this rule can only benefit the community and make it less ambiguous. If spawn trapping is blanket banned then there is no contention as to what specific kinds of spawns are disallowed and it becomes much easier for inexperienced players to play the game and for mods to enforce the rules.

**Comment by EmcPrecise** [comment]
I agree the current rule is difficult to understand and I don't like the fact it ruins the server experience for some players.
This has my support for prohibiting N/T spawn trapping.

**Comment by KarlOfDuty** [comment]
Seems like everyone are pretty positive to this, make a PR with the change and I'll approve it.

**Comment by Mineturtle795** [comment]
No, not everyone is positive to this.

**Comment by Mineturtle795** [comment]
@KarlOfDuty let me explain. I have 3 arguments.
1st, spawntrapping is vital part of emcs economy. It is the primary economic activity of me and many other players.
Secondly, spawntrapping does not hurt the community much. Most people know about the spawntrap and go there as a joke, and those who go there thinking it's a real place deserve to lose their stuff anyways.
Finally emc aims to be a earth sandbox, and on the real earth, there are many spawntrap such as syria

**Comment by Mineturtle795** [comment]
If you disable spawntrapping because it is "unfair", why not disable pvp as well as clearly it is unfair to those that have less gear and skill?

**Comment by AmphireYT** [comment]
> @KarlOfDuty let me explain. I have 3 arguments.
> 1st, spawntrapping is vital part of emcs economy. It is the primary economic activity of me and many other players.
> Secondly, spawntrapping does not hurt the community much. Most people know about the spawntrap and go there as a joke, and those who go there thinking it's a real place deserve to lose their stuff anyways.
> Finally emc aims to be a earth sandbox, and on the real earth, there are many spawntrap such as syria

Replying to your arguements
1. Quit being lazy and get your own gold. And no one cares if it your “primary source of gold” its unfair to those players who worked hared to get these items.
2. It hurts for the new players coming into the server who doesnt know anything about the server. Losing all their stuff and eventually making them quit. Also hurts for the people who doesnt have the knowledge to know what is the spawn trap is and going there, losing there stuff
3. The real earth doesnt have teleporting, and killing the person thats just messed up. And were talking about spawn trap in general. If you go to syria, your not going to get killed in a 4 by 4, people have a chance to defend them selfs.



Other comment, they dont need to pvp to be able to play this game, they could be a builder/similar jobs for the towns. And if he is a pvper, he can practice his skills. And if your the one who is suggesting that. Remove the blocks from fiji and let us fight you I wanna see how long you last.

**Comment by AmphireYT** [comment]
And sorry if i made mistakes to my spelling

**Comment by EmcPrecise** [comment]
Adding to the above, I'd like to point out the amount of players who have quit our server because "those who go there deserve to lose their stuff" is substantial , we have have many support tickets regarding this.

**Comment by Mineturtle795** [comment]
@EmcPrecise by your logic, should we disable pvp as well? Because there are always the kiddos that decide to quit emc after getting killed and losing all their shit in a fight.

**Comment by Mineturtle795** [comment]
@KarlOfDuty spawntrapping has always been a vital and everlasting part of emc. It serves as a way to filter out the retards- if someone is stupid enough to fall for a known spawntrap, surely they're not smart enough to help the server much. Furthermore, I argue that spawntrap improve the server. It creates a sense of unity and community, as every player hates the spawntrapper. Lastly, spawntrapping isn't the only unfair way of killing people. By your logic, @Highlander214, you probably think that afk killing should be bannable because the nonafk player has an advantage.

**Comment by Mineturtle795** [comment]
Furthermore, the opposition loves to talk about all the people that quit due to spawntrapping. However, if spawntrapping is disabled, many people like me that rely on it will likely quit. Players such as me, flockawacka, thiccflatty, and slackass will likely quit the server.

**Comment by AmphireYT** [comment]
> @EmcPrecise by your logic, should we disable pvp as well? Because there are always the kiddos that decide to quit emc after getting killed and losing all their shit in a fight.

Buddy, Were not disabling pvp and at least they had chance to defend themselves. Not like when your traping people and you cant do anything and just lose everything when your in a fight. Most of the time people have come prepared. Even tho they die, everything is safe um there echest because the people who think that fiji is some kind cool place, they come with their gold and o look, its gone and that how they quit. When there a fight, they know its a fight and the consequences of what would happen if you engage into that fight. PVP and spawn traping IS very different from eachother. What newbies dont know is nations could be spawn trappers. They know pvp, but not spawn trapping.

**Comment by AmphireYT** [comment]
> @KarlOfDuty spawntrapping has always been a vital and everlasting part of emc. It serves as a way to filter out the retards- if someone is stupid enough to fall for a known spawntrap, surely they're not smart enough to help the server much. Furthermore, I argue that spawntrap improve the server. It creates a sense of unity and community, as every player hates the spawntrapper. Lastly, spawntrapping isn't the only unfair way of killing people. By your logic, @Highlander214, you probably think that afk killing should be bannable because the nonafk player has an advantage.

Look, there not retards, there brand new people who dont know much about the game. If lets say new york becomes a spawn trap, how the hell is someone suppose to know if its a spawn trap or not? and if everyone hates it, remove it.
and were talking about trapping not afk killing thats another whole thing

**Comment by AmphireYT** [comment]
> Furthermore, the opposition loves to talk about all the people that quit due to spawntrapping. However, if spawntrapping is disabled, many people like me that rely on it will likely quit. Players such as me, flockawacka, thiccflatty, and slackass will likely quit the server.

Please quit. No one (no offense) Wants you in the server. Your not giving the server anything thats beneficial and that supports server, Your just making people quit and making mods do more work dealing with tickets. (flockawacka we chill doe I still want you). The server will be better without  spawntrappering.

**Comment by jkmartindale** [comment]
I'm messed up in the head and I enjoy visiting spawntraps to mess around, but I wouldn't miss them if they were gone.

> sending multiple msgs advertising a trap should be prohibited

This is one of the biggest ways spawntrapping impacts players, including those who avoid spawntraps or always visit nations naked. Yeah, it's a funny meme when you read "free beacons at n spawn fiji xddd" once or twice. But when chat is filled with multiple messages per minute advertising a spawntrap, it's objectively annoying and detracts from everyone's experience. If there was a way to only temporarily `/ignore` someone I'd use it a lot more often.

> spawntrapping is vital part of emcs economy

Don't confuse something being a vital part of your income with something being a vital part of the economy. Spawntrappers are in the strong minority on the server, so ruling it out as a source of income is not going to impact anyone's opportunities at getting income. From my understanding, most of the income that reaches spawntrappers stays with them. Gold gets hoarded and items get resold. Economies only work when people are actively trading and money is moving. I'm not saying we should forcefully disallow gold hoarding, I'm just saying that activities that encourage hoarding shouldn't be treated as an essential part of the economy, because they are the opposite.

> spawntrapping has always been a vital and everlasting part of emc

So is gg0vi spam but that isn't sufficient reason to unban him either.

> if someone is stupid enough to fall for a known spawntrap, surely they're not smart enough to help the server much

If someone is lazy enough to spend most of their time spawntrapping, surely they're not useful enough to help the server much? Most of the spawntraps I know about are husks around the home of one or two residents and don't benefit more than a few people.

> spawntrapping does not hurt the community much
> Players such as me, flockawacka, thiccflatty, and slackass will likely quit the server.

Don't conflate a few notable players with the entire community. The only times someone being popular drives players to the server is if they're a streamer/YouTuber with a following. Few people would miss spawntrappers if they up and yeeted themselves off the server (did anyone miss F5?). EarthMC is ultimately a business, and being able to retain new players means more players buying priority and helping to keep the server running. As was mentioned earlier, there's hard data on how many players have left the server due to spawntrapping, and that hurts both EarthMC's bottom line and towns/nations trying to keep active residents.

> emc aims to be a earth sandbox

If you want a sandbox environment, there's room in the 2b2t queue. If EMC was a true sandbox then sure spawntrapping would be allowed but visitors would also have full build/destroy permissions.

> why not disable pvp as well as clearly it is unfair to those that have less gear and skill?

You can fix weaker gear by buying/trading and you can fix weaker skill by practicing. You can't fix not having the same permissions as your trapper. Spawntrapping is different from regular PVP because players are placed in a position where they physically cannot move around, and in some cases (such as South Africa and Fiji from a few months ago) physically cannot attack the trapper. PVP takes place in an open environment while spawntrapping takes place in a cage. I would back a rule allowing open PVP spawns and spawntrapping if there was a certain minimum distance visitors could move within the spawn point, because that brings it closer to real PVP.

**Comment by DasCodes** [comment]
Ref: #98.
